### ISSUE TITLE
ava tests don't work with module import path contains "@/pathname" which is supported by poi

### ISSUE THREAD

**Issue by Rayraegah** [egoist/create-vue-app#24]
One of the things I like about `Poi`, is a feature to use `@` to target the source root in module imports.

Example:

`@/store/mutation-types`

instead of 

`../../../store/mutation-types`

but `AVA` tests cannot resolve paths with `@` in them because its web-pack specific. Is there a work around for it?

might switch to https://github.com/egoist/tyu for testing if its too much trouble to make ava work. tyu has the right configuration in jest wrapper.
```
    moduleNameMapper: {
      '^@/(.*)$': '<rootDir>/src/$1'
    }
```

**Comment by egoist** [comment]
You can use https://github.com/egoist/poi/tree/master/packages/poi-preset-transform-test-files to transform test files before actually running it.

Jest (Tyu) might be a better option for webpack projects.

**Comment by Rayraegah** [comment]
it works
