### ISSUE TITLE
--type=web ??

### ISSUE THREAD

**Issue by boustanihani** [egoist/create-vue-app#3]
In the example we see `--type=web`. Are there any other types supported?

I think this should be added to the docs.

**Comment by egoist** [comment]
<img width="458" alt="2017-03-12 5 54 38" src="https://cloud.githubusercontent.com/assets/8784712/23830747/fe42e88a-074c-11e7-80b2-93885f576433.png">

You can omit it to use the interactive interface. Maybe add docs about this later.

**Comment by egoist** [comment]
Added https://github.com/egoist/create-vue-app#cli-args
