### ISSUE TITLE
create-vue-app vs vue-cli

### ISSUE THREAD

**Issue by franciscolourenco** [egoist/create-vue-app#6]
Hi, how does this tool compare, and does it make sense to use it when there is vue-cli / sao?

**Comment by egoist** [comment]
Just treat this as `create-react-app` but for Vue 😅 while vue-cli is something like yeoman

**Comment by franciscolourenco** [comment]
Should we be duplicating concepts from react culture, when we already have other more versatile tools for project quick starting? Shouldn't you transform this into a vue-cli / sao template, or point people to one? 😅

**Comment by franciscolourenco** [comment]
Also, should vbuild reccomend using create-vue-app for scaffolding? Seems like you went into opposite directions with `create-vue-app` and `sao`.

**Comment by egoist** [comment]
Hi, now `create-vue-app` is refactored to be a wrapper of `sao` and [`template-vue`](https://github.com/egoist/template-vue), you can reopen this if you still have questions :D
