### ISSUE TITLE
win7 cmd create error;

### ISSUE THREAD

**Issue by dean5277** [egoist/create-vue-app#7]
**system**:win7;
**error**:The filename, directory name, or volume slogan method is not correct.

![image](https://cloud.githubusercontent.com/assets/1802631/24787747/b982a528-1b9c-11e7-9532-200fbaa674d5.png)

**Comment by egoist** [comment]
Please reopen this if it still happens.

**Comment by dean5277** [comment]
the problem still happens

**Comment by egoist** [comment]
Are you using latest version? only `create-vue-app` is available now, it works fine for me on windows 10

**Comment by dean5277** [comment]
![image](https://user-images.githubusercontent.com/1802631/27379161-d0235354-56ac-11e7-9663-004673fb63c6.png)
