### ISSUE TITLE
How to pass env variables to vue application?

### ISSUE THREAD

**Issue by MykytaLiashenko** [egoist/create-vue-app#8]
Hi. I need to pass api url to vue application for vue-resource .
I tried `--env.VARIABLE_NAME xxx` and `VARIABLE_NAME=xxx yarn dev` but nothing works.

**Comment by egoist** [comment]
Just tested it, `vbuild --env.VARIABLE_NAME xxx`  should work.

**Comment by MykytaLiashenko** [comment]
What about `yarn dev` command?

**Comment by egoist** [comment]
You need to update npm scripts in `package.json`.

Or `yarn dev -- [extra arguments]` like `yarn dev -- --env.VARIABLE_NAME xxx` for temporary use.

**Comment by MykytaLiashenko** [comment]
`yarn dev -- [extra arguments]` is the best solution.
Thanks.
