### ISSUE TITLE
Creating custom html output.

### ISSUE THREAD

**Issue by MykytaLiashenko** [egoist/create-vue-app#9]
Using vbuild we could change html output in html-webpack-plugin options according to docs.
Do we have such ability with create-vue-app?

In my case I need to add some google fonts for Material Design.

**Comment by egoist** [comment]
Basically it's just a boilerplate for vbuild, so `html` option for vbuild also works here, the easiest way is to create an `index.html` at root directory and vbuild will load it automatically.

**Comment by MykytaLiashenko** [comment]
Works cool.
Thanks

We might need to add more documentation for create-vue-app.
